接続スクリプトを更新
soracom/handson pull request #65
Opened 2018-05-16 06:26 UTC by chiemit

USBドングルの接続スクリプトを最新の setup_air.sh に変更します。合わせて、関連する部分の文言を修正します。

2018-05-23 05:35 UTC, j3tm0t0 requested changes
wvdial  & usb-modeswitch のインストール項目は削っちゃいますか

2018-05-23 05:35 UTC, j3tm0t0 commented on plant-observation/kit.md
> +上記の例で出力されたファイルは、 http://raspberrypi.local/timelapse.mp4 でアクセスする事が出来ます。
good catch!

2018-05-23 05:35 UTC, j3tm0t0 commented on plant-observation/seminar.md
> +sudo apt-get install -y usb-modeswitch wvdial
(ここだけに限らずだけど)setup_air.sh 内で usb-modeswitch / wvdial は(必要に応じて)インストールされるから、パッケージのインストールパートは削ってしまってもよかったりします

2018-05-23 06:49 UTC, chiemit commented
@j3tm0t0 確認ありがとうございました！wvdial & usb-modeswitch のインストール項目を削りました。

2018-05-29 02:22 UTC, j3tm0t0 approved these changes

2018-05-29 02:22 UTC, merged